name: Build and Deploy
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron: '5 16 * * *'  # every day at 16:05 UTC

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Remove gitignore in data
        run: rm data/.gitignore

      - name: Update Data
        run: |
          python scripts/fetch-angels.py
          python scripts/fetch-events.py

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: . # The folder the action should deploy.
