name: Build and Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: '17 23 * * *'  # every day at 23:17 (at 17 minutes after full hour to avoid spikes)
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Remove gitignore in data
        run: rm data/.gitignore

      - name: Update Data
        run: |
          python scripts/fetch-angels.py
          python scripts/fetch-events.py

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: . # The folder the action should deploy.
