name: Build and Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron: '17 * * * *'  # every hour at 17 mins (to avoid spikes e.g. at the beginning of each hour)
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          ref: master

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Remove gitignore in data
        run: rm data/.gitignore

      - name: Update Data
        run: |
          python scripts/fetch-angels.py
          python scripts/fetch-events.py

      - name: Check for changes in data files when scheduled
        id: check_for_changes
        if: ${{ github.event_name == 'schedule' }}
        run: |
          git add data # git diff does not work on unversioned files
          git diff --quiet --exit-code origin/gh-pages -- data
          echo "::set-output name=has_changes::$?"

      - name: Deploy on push or if scheduled and has changes
        if: ${{ github.event_name != 'schedule' || steps.check_for_changes.outputs.has_changes }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: . # The folder the action should deploy.
